server:
  port: ${PORT:8080}
spring:
  application:
    name: "MSAuthentication"
  devtools:
    add-properties: false
  profiles:
    include: null
  r2dbc:
    schema:
      create-mode: "always"
      locations: "classpath:schema.sql"
  sql:
    init:
      mode: "always"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

routes:
  paths:
    users: "/api/v1/usuarios"
    userById: "/api/v1/usuario/{id}"
    userByDocId: "/api/v1/usuario/{docId}"
    userLogin: "/api/v1/login"
    usersByEmail: "/api/v1/usuarios-by-email"

adapters:
  r2dbc:
    host: ${SPRING_DATASOURCE_HOST}
    port: ${SPRING_DATASOURCE_PORT}
    database: ${SPRING_DATASOURCE_DATABASE}
    schema: "public"
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
